### ISSUE TITLE
User Publishings

### ISSUE THREAD

**Issue by josepablofm78** [nevermined-io/defi-marketplace#243]
In order to enrich the quality of the data in the marketplace and to get traction in the community, the platform should allow the users to publish their own assets.

The Defi marketplace or Nevermined won't act as a centralized store, no user's asset will be persisted in Nevermined infrastructure

- [x] Provide a form to define the metadata related with the asset and to publish it in the marketplace
- [x] Implement this publish form in a multistep way
- [x] Allow to publish different types of assets; data, algorithms, notebooks, ...
- [x] Show different set of attributes depending on the asset type
- [x] Allow the users to publish a new asset specifying an Id from a decentralized store (filecoin, IPFS)
- [x] Provide a formulary to publish an asset located in a local computer.  The asset will be upload to a decentralized store
- [x] Implement a robust and reusable component to upload local files to Filecoin
- [x] If users provide filecoin/ipfs IDs, check the file actually exists
- [x] Allow to add multiple files to the assets
- [x] Show a popup to inform the user that files are being uploaded to Filecoin
- [x] Show a popup to inform the file is being verified when the user adds a Filecoin ID
- [x] The new asset should be publish as a 721 NFT, where the address depends on the subscription Tier selected
- [x] https://github.com/nevermined-io/defi-marketplace/issues/294
- [x] Parse error messages in a modal window
