### ISSUE TITLE
Bookmarks

### ISSUE THREAD

**Issue by josepablofm78** [nevermined-io/defi-marketplace#244]
The users should be able to bookmark assets and other users profiles they are interested in with the idea of purchase, or subscribe, later.

- [x] The users should bookmark an asset from the list of results in Browse page or from the Details screen
- [x] Profile screen should have a tab to show the bookmarked assets
- [x] The users will be able to remove a bookmark
- [x] The users should access the details of an asset  from the bookmark
- [x] the users could purchase an asset directly from the bookmark list
