### ISSUE TITLE
Modify Search and Browse

### ISSUE THREAD

**Issue by josepablofm78** [nevermined-io/defi-marketplace#246]
The Browse page and the filtering capabilities are completely coupled with the protocols we are currently getting data from.

If the new version of the marketplace allows users to publish their own assets we need to rethink the categories and filters in the search functionality

- [ ] Design and implement new filters 
- [ ] Show new fields in the list of results: type of asset (dataset, notebook, ...), owner of the asset
- [ ] Allow to bookmark an asset from the list of results
- [ ] Allow to access to User/Organization details
