### ISSUE TITLE
Integrate `catalog` in DeFi Marketplace

### ISSUE THREAD

**Issue by aaitor** [nevermined-io/defi-marketplace#272]
Tasks:

- [x] https://github.com/nevermined-io/defi-marketplace/issues/271
- [x] Integrate the assets publishing
- [x] Purchase NFT subscription
- [x] Check if is a NFT (ERC-721) holder
- [x] Download of files
