### ISSUE TITLE
Integrate the catalog in the marketplace

### ISSUE THREAD

**Issue by aaitor** [nevermined-io/defi-marketplace#275]
Components to integrate (sorted by priority):

- [ ] Wallet authentication (existing in catalog)
- [ ] Is NFT Holder?  **(doesn't existing in catalog)** 
- [ ] Purchase a NFT (existing in catalog)
- [ ] Download files associated in an asset **(doesn't existing in catalog)**
- [ ] Edit user profile **(doesn't existing in catalog)**
- [ ] Asset publication with NFT associated **(doesn't existing in catalog)**

**Out of scope** in this story: Bookmarks, Search, etc

**Comment by aaitor** [comment]
dupe #272
